catalog:
  '@effect/typeclass': ^0.36.0
  '@effect/vitest': ^0.25.1
  'effect-ts-folds': ^1.0.28
  '@eslint/js': ^9.34.0
  '@fast-check/vitest': ^0.2.2
  '@griffel/react': ^1.5.30
  '@tsconfig/node24': ^24.0.1
  '@tsconfig/strictest': ^2.0.5
  '@types/node': ^24.3.0
  '@vitest/coverage-v8': ^3.2.4
  dependency-cruiser: ^17.0.1
  effect-ts-laws: ^1.3.17
  effect: ^3.17.11
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-sonarjs: ^3.0.5
  eslint-plugin-unicorn: ^60.0.0
  eslint: ^9.34.0
  fast-check: ^4.3.0
  globals: ^16.3.0
  jiti: ^2.5.1
  prettier: ^3.6.2
  tsx: ^4.20.5
  tty-strings: ^1.5.2
  typedoc: ^0.28.12
  typescript-eslint: ^8.42.0
  typescript: ^5.9.2
  vite: ^7.1.4
  vitest: 3.2.4

onlyBuiltDependencies:
  - esbuild
