#!/usr/bin/env bash

if [[ -z "${PNPM_SCRIPT_SRC_DIR:-}" ]]; then
  echo "No PNPM_SCRIPT_SRC_DIR found. Please run from pnpm." >&2
  exit 1
fi

export DIR="${PNPM_SCRIPT_SRC_DIR}"
export NAME="$(basename "${PNPM_SCRIPT_SRC_DIR}")"
export EXAMPLES_NAME=examples
export INLINE_EXAMPLES_NAME=inline
export MARKDOWN_EXAMPLES_NAME=markdown
export INLINE_EXAMPLES_RELATIVE="${EXAMPLES_NAME}/${INLINE_EXAMPLES_NAME}"

function prepare() {
  local dir
  dir="${1}"
  export PACKAGE_JSON="${dir}/package.json"
  export SRC_DIR="${dir}/src"
  export CONFIG_DIR="${dir}/config"
  export DIST_DIR="${dir}/dist"
  export API_DOCS_DIR="${dir}/api-docs"
  export ICON_DIR="${dir}/public/icons"
  export ICON_INDEX_DIR="${dir}/src/icons"
  export DEV_DIR="${dir}/dev"
  export COVERAGE_DIR="${API_DOCS_DIR}/coverage"
  export EXAMPLES_DIR="${dir}/$EXAMPLES_NAME"
  export MARKDOWN_EXAMPLES_DIR="${EXAMPLES_DIR}/${MARKDOWN_EXAMPLES_NAME}"
  export INLINE_EXAMPLES_DIR="${EXAMPLES_DIR}/${INLINE_EXAMPLES_NAME}"
  export EXAMPLES_SNAPSHOT_DIR="${EXAMPLES_DIR}/.snapshots"
  export PROJECT_EXAMPLES_SNAPSHOTS="${EXAMPLES_SNAPSHOT_DIR}/project"
  export MARKDOWN_EXAMPLES_SNAPSHOTS="${EXAMPLES_SNAPSHOT_DIR}/markdown"
}

prepare "${DIR}"
