#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

dir="$(dirname "${0}")"

. "${dir}/lib/_"

typedoc --out "$API_DOCS_DIR" --options "$CONFIG_DIR"/typedoc.json

mkdir -p "$API_DOCS_DIR/coverage"

show_done 'build:docs'
