#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

. "$(dirname "${0}")/lib/_"

echo "# ⚖ Checking…"

pnpm extract:examples &
pnpm test &

wait

pnpm build &
pnpm lint:fix &
pnpm build:docs &
pnpm circular &

wait

show_done 'check'
