#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

. "$(dirname "${0}")/lib/_"

echo "# ⚖ Checking…"

pnpm test &
pnpm lint &
pnpm typecheck &
pnpm test:examples &
pnpm build:docs &
pnpm circular &

wait

show_done 'check'
