#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

. "$(dirname "${0}")/lib/_"

echo "# ⚖ Checking…"

pnpm clean

pnpm extract:inline:examples &
pnpm test:project:examples &
pnpm test:markdown:examples &

wait

pnpm coverage &
pnpm circular &
pnpm lint:fix &

wait

pnpm build
pnpm build:docs

show_done 'check'
