#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

dir="$(dirname "${0}")"

. "${dir}/lib/_"

echo -e "🏗️ Checking $(color_magenta 'inline API examples')..."

rm -rf "${INLINE_EXAMPLES_DIR}"/*

function extract() {
  local path
  path="${1}"
  sed -n '/^ \* @example/,/^ \* @/p' "${file}" |
    perl -pE 's/^ \* ?//; s/^\@example.*/---/; s/^@.*//' 
}

function perl_write() {
  local file
  file="${1}"
  echo '
my $file='"'${file}'"';
my $i=0;
my @parts = split(/^---/mg);
my $count = @parts - 1;
for my $part (@parts) {
  if ($i > 0) {
    (my $part_file = $file) =~ s/\.ts$//;
    $part_file = "$part_file.$i.ts";
    print "#      Example #$i/$count...\n";
    $part =~ s/^\n//m;
    $part =~ s/(?:\n|\s)*$//sg;
    open(my $fh, ">", $part_file) or die "Could not open file $part_file $!";
    print $fh "$part\n";
    close $fh;
  }
  $i++;
}'
}

i=1
for absolute_path in $(find "${SRC_DIR}" -name '*.ts'); do
  file="${absolute_path##*/effect-tree/}"
  if [[ "${file}" =~ test\.ts$ ||
        "${file}" =~ /test/    ||
        "${file}" =~ ^src/util ]]; then continue; fi
  src_path="${file##src/}"
  label="$(color_path "${src_path}")"
  example="$(extract "${file}")";

  if [[ "$example" != "" ]]; then
    log "$(printf '%3d' $i). Extracting examples from ${label}"
    path="${src_path%/*}"
    mkdir -p "${INLINE_EXAMPLES_DIR}/${path}"
    examples_file="${INLINE_EXAMPLES_DIR}/${src_path}"
    echo "${example}" > "${examples_file}"
    perl -0777 -ne "$(perl_write "${examples_file}")" "${examples_file}"
    ((++i))
    rm "${examples_file}"
  fi
done

echo -e "✅ $(color_green Done) extracting $(color_magenta 'inline API examples')."

echo -e "🏗️ Linting $(color_magenta 'inline API examples')..."

pnpm lint --fix examples/inline

echo -e "✅ $(color_green Done) linting $(color_magenta 'inline API examples')."

show_done 'test-inline'

