#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

. "$(dirname "${0}")/lib/_"

docs="../${NAME}-docs"

cp -r "$API_DOCS_DIR"/* "$docs"

pushd "$docs"
git add .
git commit -m 'doc update'
git push
popd

show_done 'publish:docs'
