#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

dir="$(dirname "${0}")"

. "$dir/lib/_"

"$dir/coverage"

mkdir -p "$COVERAGE_REPORT_DIR"
cp -r "$COVERAGE_DIR" "$COVERAGE_REPORT_DIR"

"${dir}/build-docs"

docs="../${NAME}-docs"

cp -r "$API_DOCS_DIR"/* "$docs"

pushd "$docs"
git add .
git commit -m 'doc update'
git push
popd

show_done 'publish:docs'
