#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

dir="$(dirname "${0}")"

. "${dir}/lib/_"

echo -e "🏗️ Testing $(color_magenta 'inline API examples')..."

rm -rf "${INLINE_EXAMPLES_DIR}"/*

"$(dirname "${0}")/extract-inline-examples" "${INLINE_EXAMPLES_RELATIVE}"

echo -e "✅ $(color_green Done) extracting $(color_magenta 'inline API examples')."

"$(dirname "${0}")/test-watch" run "${@}" examples/inline

show_done 'test:inline:examples'

