import {defineConfig} from 'vitest/config'

export default defineConfig({
  test: {
    typecheck: {
      enabled: true,
    },
    include: [
      './src/**/*.test.ts',
      './src/**/*.test-d.ts',
      './examples/inline/**/*.test.ts',
    ],
    coverage: {
      provider: 'v8',
      reportsDirectory: './node_modules/.coverage',
      exclude: [
        'api-docs',
        'config',
        'dev',
        'dist',
        'examples/*.ts',
        'examples/markdown/**/*.ts',
        'index.ts',
        'src/**/*.test-d.ts',
        'src/**/*.test.ts',
        'src/**/types.ts',
        'src/arbitrary',
        'src/arbitrary.ts',
        'src/codec.ts',
        'src/codec/arrays.ts',
        'src/codec/edges.ts',
        'src/codec/indented.ts',
        'src/codec/paths.ts',
        'src/codec/prufer.ts',
        'src/draw.ts',
        'src/draw/index.ts',
        'src/draw/part.ts',
        'src/draw/parts.ts',
        'src/draw/glyph.ts',
        'src/draw/variants.ts',
        'src/draw/partF.ts',
        'src/draw/tree.ts',
        'src/draw/tree/theme.ts',
        'src/draw/struts.ts',
        'src/draw/align.ts',
        'src/folds.ts',
        'src/instances.ts',
        'src/ops.ts',
        'src/schemes.ts',
        'src/schemes/fold.ts',
        'src/schemes/unfold.ts',
        'src/test',
        'src/test.ts',
        'src/tree.ts',
        'src/treeF.ts',
        'src/unfolds.ts',
        'src/util',
        'src/util.ts',
        'src/zipper.ts',
      ],
    },
  },
})
